### PR TITLE
updates to make sending text and sending files working with the latest version of Dbus API

### PR DESCRIPTION
**Pull request by 8go**
Updated some parts to reflect the changes to the Dbus API.

Made send text message and send file work
 - corrected sendfile.py and added new sendmsg.py

Added README to help user

Tested with one peer on Fedora 40 and another peer on Android

### CODE REVIEW

**Comment by nicos44k** [comment]
Hi, I'm working on the Jami team, thank you for the PR, your work is really appreciated ! :star_struck: 
However this is a Github mirror. Please upload to the main project here: https://git.jami.net/savoirfairelinux/jami-daemon

**Comment by 8go** [comment]
Ok, I tried. 

I created an account, logged in, set up 2FA, recovrey codes, etc, etc.

Then I tried to fork jami-daemon repo. And it gave error:

`Limit reached You cannot create projects in your personal namespace. Contact your GitLab administrator.`

I am not paying for gitlab. Is that why? How can I fork?

On the main repo page "Fork" is grayed out, disabled? That is where one usually creates the fork, no?

Since that did not work, I clicked the "0" next to the "grayed-out Fork" button. A page listing zero forks comes up. 
On this page there is a blue "Fork" button that is enabled. 
There I click and get the above error.

If I cannot fork obviously I cannot submit the PR.

Any ideas?

**Comment by 8go** [comment]
On my https://git.jami.net/dashboard/projects account I cannot see a way to create a simple dummy project. 

This account cannot create a repo? Hence it cannot fork? 

I logged in with "github" and then followed all steps to create an account with everythin including access tokens. 

I could raise an "issue" on your repo.

**Comment by nicos44k** [comment]
Hi, this message just to let you know I'll look on this monday. 👍

**Comment by 8go** [comment]
Thank you.

On another topic, just FYI, I wrote a simple and incomplete CLI tool in Python. 
See https://github.com/8go/jami-commander/

The advantage is that the tool is packaged via `pip install jami-commander` and hence easy for newcomers to install and run.

**Comment by AmarOk1412** [comment]
you want to use review.jami.net, not gitlab's jami. GitLab is also a mirror.

**Comment by nicos44k** [comment]
> Then I tried to fork jami-daemon repo.

`jami-daemon` is a repository hosted on a private GitLab instance `git.jami.net`.
You cannot create any project on this server. I think you don't need to.

> GitLab is also a mirror.

Yep, sotty, you have to submit changes via `Gerrit` (review.jami.net).  See https://docs.jami.net/en_US/developer/new-developers/working-with-gerrit.html

**Comment by 8go** [comment]
All correct. 

review.jami.net was the answer. The PR shows up there now. Thank you. 

I will close this PR here on github now.

**Pull request closed without merging**
